/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedEquipmentSplatRouteImport } from './routes/_authenticated/equipment/$'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings/new'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedBookingsBookingIdIndexRouteImport } from './routes/_authenticated/bookings/$bookingId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminEquipmentIndexRouteImport } from './routes/_authenticated/admin/equipment/index'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin/categories/index'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin/bookings/index'
import { Route as AuthenticatedBookingsBookingIdEditRouteImport } from './routes/_authenticated/bookings_/$bookingId/edit'
import { Route as AuthenticatedAdminEquipmentNewRouteImport } from './routes/_authenticated/admin/equipment/new'
import { Route as AuthenticatedAdminBookingsBookingIdIndexRouteImport } from './routes/_authenticated/admin/bookings/$bookingId/index'
import { Route as AuthenticatedAdminUsersUserIdEditRouteImport } from './routes/_authenticated/admin/users/$userId.edit'
import { Route as AuthenticatedAdminEquipmentEquipmentIdEditRouteImport } from './routes/_authenticated/admin/equipment/$equipmentId.edit'
import { Route as AuthenticatedAdminBookingsBookingIdEditRouteImport } from './routes/_authenticated/admin/bookings/$bookingId.edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipmentSplatRoute =
  AuthenticatedEquipmentSplatRouteImport.update({
    id: '/equipment/$',
    path: '/equipment/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBookingsBookingIdIndexRoute =
  AuthenticatedBookingsBookingIdIndexRouteImport.update({
    id: '/bookings/$bookingId/',
    path: '/bookings/$bookingId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipmentIndexRoute =
  AuthenticatedAdminEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBookingsBookingIdEditRoute =
  AuthenticatedBookingsBookingIdEditRouteImport.update({
    id: '/bookings_/$bookingId/edit',
    path: '/bookings/$bookingId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEquipmentNewRoute =
  AuthenticatedAdminEquipmentNewRouteImport.update({
    id: '/equipment/new',
    path: '/equipment/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsBookingIdIndexRoute =
  AuthenticatedAdminBookingsBookingIdIndexRouteImport.update({
    id: '/bookings/$bookingId/',
    path: '/bookings/$bookingId/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersUserIdEditRoute =
  AuthenticatedAdminUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipmentEquipmentIdEditRoute =
  AuthenticatedAdminEquipmentEquipmentIdEditRouteImport.update({
    id: '/equipment/$equipmentId/edit',
    path: '/equipment/$equipmentId/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsBookingIdEditRoute =
  AuthenticatedAdminBookingsBookingIdEditRouteImport.update({
    id: '/bookings/$bookingId/edit',
    path: '/bookings/$bookingId/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/faq': typeof AuthenticatedFaqRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/equipment/$': typeof AuthenticatedEquipmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/admin/equipment/new': typeof AuthenticatedAdminEquipmentNewRoute
  '/bookings/$bookingId/edit': typeof AuthenticatedBookingsBookingIdEditRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/equipment/': typeof AuthenticatedAdminEquipmentIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/bookings/$bookingId/': typeof AuthenticatedBookingsBookingIdIndexRoute
  '/admin/bookings/$bookingId/edit': typeof AuthenticatedAdminBookingsBookingIdEditRoute
  '/admin/equipment/$equipmentId/edit': typeof AuthenticatedAdminEquipmentEquipmentIdEditRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/admin/bookings/$bookingId/': typeof AuthenticatedAdminBookingsBookingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/faq': typeof AuthenticatedFaqRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/equipment/$': typeof AuthenticatedEquipmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
  '/admin/equipment/new': typeof AuthenticatedAdminEquipmentNewRoute
  '/bookings/$bookingId/edit': typeof AuthenticatedBookingsBookingIdEditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdIndexRoute
  '/admin/bookings/$bookingId/edit': typeof AuthenticatedAdminBookingsBookingIdEditRoute
  '/admin/equipment/$equipmentId/edit': typeof AuthenticatedAdminEquipmentEquipmentIdEditRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/admin/bookings/$bookingId': typeof AuthenticatedAdminBookingsBookingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/equipment/$': typeof AuthenticatedEquipmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/_authenticated/admin/equipment/new': typeof AuthenticatedAdminEquipmentNewRoute
  '/_authenticated/bookings_/$bookingId/edit': typeof AuthenticatedBookingsBookingIdEditRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/equipment/': typeof AuthenticatedAdminEquipmentIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/bookings/$bookingId/': typeof AuthenticatedBookingsBookingIdIndexRoute
  '/_authenticated/admin/bookings/$bookingId/edit': typeof AuthenticatedAdminBookingsBookingIdEditRoute
  '/_authenticated/admin/equipment/$equipmentId/edit': typeof AuthenticatedAdminEquipmentEquipmentIdEditRoute
  '/_authenticated/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
  '/_authenticated/admin/bookings/$bookingId/': typeof AuthenticatedAdminBookingsBookingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/faq'
    | '/profile'
    | '/api/telegram'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/bookings/new'
    | '/equipment/$'
    | '/api/auth/$'
    | '/api/images/$'
    | '/bookings/'
    | '/equipment/'
    | '/admin/equipment/new'
    | '/bookings/$bookingId/edit'
    | '/admin/bookings/'
    | '/admin/categories/'
    | '/admin/equipment/'
    | '/admin/users/'
    | '/bookings/$bookingId/'
    | '/admin/bookings/$bookingId/edit'
    | '/admin/equipment/$equipmentId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/bookings/$bookingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/faq'
    | '/profile'
    | '/api/telegram'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/bookings/new'
    | '/equipment/$'
    | '/api/auth/$'
    | '/api/images/$'
    | '/bookings'
    | '/equipment'
    | '/admin/equipment/new'
    | '/bookings/$bookingId/edit'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/equipment'
    | '/admin/users'
    | '/bookings/$bookingId'
    | '/admin/bookings/$bookingId/edit'
    | '/admin/equipment/$equipmentId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/faq'
    | '/_authenticated/profile'
    | '/api/telegram'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/settings'
    | '/_authenticated/bookings/new'
    | '/_authenticated/equipment/$'
    | '/api/auth/$'
    | '/api/images/$'
    | '/_authenticated/bookings/'
    | '/_authenticated/equipment/'
    | '/_authenticated/admin/equipment/new'
    | '/_authenticated/bookings_/$bookingId/edit'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/equipment/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/bookings/$bookingId/'
    | '/_authenticated/admin/bookings/$bookingId/edit'
    | '/_authenticated/admin/equipment/$equipmentId/edit'
    | '/_authenticated/admin/users/$userId/edit'
    | '/_authenticated/admin/bookings/$bookingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipment/$': {
      id: '/_authenticated/equipment/$'
      path: '/equipment/$'
      fullPath: '/equipment/$'
      preLoaderRoute: typeof AuthenticatedEquipmentSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bookings/$bookingId/': {
      id: '/_authenticated/bookings/$bookingId/'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId/'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipment/': {
      id: '/_authenticated/admin/equipment/'
      path: '/equipment'
      fullPath: '/admin/equipment/'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bookings_/$bookingId/edit': {
      id: '/_authenticated/bookings_/$bookingId/edit'
      path: '/bookings/$bookingId/edit'
      fullPath: '/bookings/$bookingId/edit'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/equipment/new': {
      id: '/_authenticated/admin/equipment/new'
      path: '/equipment/new'
      fullPath: '/admin/equipment/new'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/$bookingId/': {
      id: '/_authenticated/admin/bookings/$bookingId/'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsBookingIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/$userId/edit': {
      id: '/_authenticated/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipment/$equipmentId/edit': {
      id: '/_authenticated/admin/equipment/$equipmentId/edit'
      path: '/equipment/$equipmentId/edit'
      fullPath: '/admin/equipment/$equipmentId/edit'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentEquipmentIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/$bookingId/edit': {
      id: '/_authenticated/admin/bookings/$bookingId/edit'
      path: '/bookings/$bookingId/edit'
      fullPath: '/admin/bookings/$bookingId/edit'
      preLoaderRoute: typeof AuthenticatedAdminBookingsBookingIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminEquipmentNewRoute: typeof AuthenticatedAdminEquipmentNewRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
  AuthenticatedAdminEquipmentIndexRoute: typeof AuthenticatedAdminEquipmentIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminBookingsBookingIdEditRoute: typeof AuthenticatedAdminBookingsBookingIdEditRoute
  AuthenticatedAdminEquipmentEquipmentIdEditRoute: typeof AuthenticatedAdminEquipmentEquipmentIdEditRoute
  AuthenticatedAdminUsersUserIdEditRoute: typeof AuthenticatedAdminUsersUserIdEditRoute
  AuthenticatedAdminBookingsBookingIdIndexRoute: typeof AuthenticatedAdminBookingsBookingIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminEquipmentNewRoute: AuthenticatedAdminEquipmentNewRoute,
  AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
  AuthenticatedAdminCategoriesIndexRoute:
    AuthenticatedAdminCategoriesIndexRoute,
  AuthenticatedAdminEquipmentIndexRoute: AuthenticatedAdminEquipmentIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedAdminBookingsBookingIdEditRoute:
    AuthenticatedAdminBookingsBookingIdEditRoute,
  AuthenticatedAdminEquipmentEquipmentIdEditRoute:
    AuthenticatedAdminEquipmentEquipmentIdEditRoute,
  AuthenticatedAdminUsersUserIdEditRoute:
    AuthenticatedAdminUsersUserIdEditRoute,
  AuthenticatedAdminBookingsBookingIdIndexRoute:
    AuthenticatedAdminBookingsBookingIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
  AuthenticatedEquipmentSplatRoute: typeof AuthenticatedEquipmentSplatRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
  AuthenticatedBookingsBookingIdEditRoute: typeof AuthenticatedBookingsBookingIdEditRoute
  AuthenticatedBookingsBookingIdIndexRoute: typeof AuthenticatedBookingsBookingIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
  AuthenticatedEquipmentSplatRoute: AuthenticatedEquipmentSplatRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  AuthenticatedBookingsBookingIdEditRoute:
    AuthenticatedBookingsBookingIdEditRoute,
  AuthenticatedBookingsBookingIdIndexRoute:
    AuthenticatedBookingsBookingIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
